// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpMS8dRIGc6nB0pRLFMcvchXRFSIYaPrM',
    appId: '1:168918734235:web:5a04a0093d0ee5b4657d3e',
    messagingSenderId: '168918734235',
    projectId: 'mini-game-app-7c442',
    authDomain: 'mini-game-app-7c442.firebaseapp.com',
    storageBucket: 'mini-game-app-7c442.firebasestorage.app',
    measurementId: 'G-BRE95SNLF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS4PA2DYU6WGWkah59N_zjzsl9Wt8J8s8',
    appId: '1:168918734235:android:89950b6126290369657d3e',
    messagingSenderId: '168918734235',
    projectId: 'mini-game-app-7c442',
    storageBucket: 'mini-game-app-7c442.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK_gXQKPX_hV-hmGGZcmMnKXTAEz4CZF4',
    appId: '1:168918734235:ios:3ce8ea7d90f0579e657d3e',
    messagingSenderId: '168918734235',
    projectId: 'mini-game-app-7c442',
    storageBucket: 'mini-game-app-7c442.firebasestorage.app',
    iosBundleId: 'com.example.miniGameApp',
  );
}
